/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/
#include<iostream>
#include<string>
using namespace std;
// hash map 
class Solution {
public:
	char findTheDifference(string s, string t) {
		int in[26] = { 0 };
		for (char c : s) {
			in[c - 'a'] += 1;
		}
		for (char c : t) {
			if (in[c - 'a'] == 0)
				return c;
			else {
				in[c - 'a']--;
			}
		}
		return 'A';
	}
};